server:
  port: 9090

spring:
  application:
    name: ms-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/facturacion-realm
      client:
        provider:
          ms-gateway:
            issuerUri: http://localhost:8080/realms/facturacion-realm
        registration:
          ms-gateway:
            provider: ms-gateway
            clientId: gateway-client
            clientSecret: gateway-secret
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:9090/login/oauth2/code/keycloak
            scope:
              - openid
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-bills
          uri: http://localhost:8085
          predicates:
            - Path=/bills/**
        - id: ms-users
          uri: http://localhost:8086
          predicates:
            - Path=/users/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org:
      springframework:
        security: DEBUG